Question 1(a):
Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [2]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 6, 4, 5])
rev_arr=np.flip(arr)

In [ ]:
print(rev_arr)

[5 4 6 3 2 1]


Question 1(b): Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods

In [ ]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

In [ ]:
arr2=array1.flatten()
print('Flatten using flatten()',arr2)
arr3=array1.ravel()
print('Flatten using ravel()',arr3)


Flatten using flatten() [1 2 3 2 4 5 1 2 3]
Flatten using ravel() [1 2 3 2 4 5 1 2 3]


Question 1(c): Compare the following numpy arrays:

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[1, 2], [3, 4]])

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [ ]:
is_equal=np.all(arr1==arr2)
print(is_equal)

True


Question 1(d): Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])


In [ ]:
most_freq_x=np.bincount(x).argmax()
most_freq_y=np.bincount(y).argmax()
index_x=np.where(x == most_freq_x)[0]
index_y=np.where(y == most_freq_y)[0]
print('Most freq in x is ',most_freq_x,' and index is ',index_x)
print('Most freq in y is ',most_freq_y,' and index is ',index_y)

Most freq in x is  1  and index is  [0 5 7 8 9]
Most freq in y is  1  and index is  [0 1 2]


Question 1(e): For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find

i. Sum of all elements

ii. Sum of all elements row-wise

iii. Sum of all elements column-wise

In [ ]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

In [ ]:
sum=np.sum(gfg)
sum_row=np.sum(gfg,axis=1)
sum_col=np.sum(gfg,axis=0)
print('Total Sum ',sum)
print('Row Sum ',sum_row)
print('Column Sum ',sum_col)

Total Sum  45
Row Sum  [[14]
 [16]
 [15]]
Column Sum  [[20  9 16]]


Question 1(f): For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find

i. Sum of diagonal elements

ii. Eigen values of matrix

iii. Eigen vectors of matrix

iv. Inverse of matrix

v. Determinant of matrix


In [ ]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])

In [ ]:
sum_diagonal = np.trace(n_array)
eigenvalues, eigenvectors = np.linalg.eig(n_array)
inverse_matrix = np.linalg.inv(n_array)
determinant = np.linalg.det(n_array)

print('diagnol sum is ',sum_diagonal)
print('eiganvalues are ',eigenvalues)
print('eigen vectors are \n', eigenvectors)
print('inverse of the matrix is \n', inverse_matrix)
print('determinant ', determinant)

diagnol sum is  176
eiganvalues are  [98.16835147 28.097044   49.73460452]
eigen vectors are 
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
inverse of the matrix is 
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
determinant  137180.0000000001


Question 1(g): Multiply the following matrices and also find covariance between matrices using NumPy:

i. p = [[1, 2], [2, 3]]

  q = [[4, 5], [6, 7]]

ii. p = [[1, 2], [2, 3], [4, 5]]

  q = [[4, 5, 1], [6, 7, 2]]


In [ ]:
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

In [ ]:
prod_1=np.dot(p1,q1)
covar_1 = np.cov(p1.flatten(), q1.flatten())
prod_2=np.dot(p2,q2)
covar_2 = np.cov(p2.flatten(), q2.flatten())
print('product of matrix 1\n',prod_1)
print('product of matrix 2\n',prod_2)
print('covariance of matrix 1\n',covar_1)
print('covariance of matrix 2\n',covar_2)


product of matrix 1
 [[16 19]
 [26 31]]
product of matrix 2
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
covariance of matrix 1
 [[0.66666667 1.        ]
 [1.         1.66666667]]
covariance of matrix 2
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


Question 1(h): For the matrices:
x = np.array([[2, 3, 4], [3, 2, 9]]);
y = np.array([[1, 5, 0], [5, 10, 3]]),

find inner, outer and cartesian product?

In [ ]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

In [ ]:
inner_product = np.inner(x, y)
outer_product = np.outer(x, y)
print('inner product\n',inner_product)
print('outer product\n',outer_product)

inner product
 [[17 52]
 [13 62]]
outer product
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


In [ ]:
x_flat = x.flatten()
y_flat = y.flatten()
xx, yy = np.meshgrid(x_flat, y_flat)
print('cartesian product is \n',np.vstack([xx.ravel(), yy.ravel()]).T)


cartesian product is  [[ 2  1]
 [ 3  1]
 [ 4  1]
 [ 3  1]
 [ 2  1]
 [ 9  1]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2  0]
 [ 3  0]
 [ 4  0]
 [ 3  0]
 [ 2  0]
 [ 9  0]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2 10]
 [ 3 10]
 [ 4 10]
 [ 3 10]
 [ 2 10]
 [ 9 10]
 [ 2  3]
 [ 3  3]
 [ 4  3]
 [ 3  3]
 [ 2  3]
 [ 9  3]]


Question 2(a): For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])

i. Find element-wise absolute value

ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row.

iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row

In [3]:
array = np.array([[1, -2, 3], [-4, 5, -6]])

In [4]:
abs_array = np.abs(array)
print("absolute value: ", abs_array)


absolute value:  [[1 2 3]
 [4 5 6]]


In [5]:
arr1 = array.flatten()
arr2 = np.percentile(arr1, [25, 50, 75])
print("percentiles of flattened array: ",arr2)
arr3 = np.percentile(array, [25, 50, 75], axis=0)
print("percentiles for each column:", arr3)
arr4 = np.percentile(array, [25, 50, 75], axis=1)
print("ercentiles for each row: ",arr4)

percentiles of flattened array:  [-3.5 -0.5  2.5]
percentiles for each column: [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
ercentiles for each row:  [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [6]:
mean = np.mean(arr1)
median= np.median(arr1)
std = np.std(arr1)
print("Mean, Median, and Standard Deviation:")
print(mean, median, std)

mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_columns = np.std(array, axis=0)
print("Mean, Median, and Standard Deviation for each column:")
print(mean_columns, median_columns, std_columns)

mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)
print("Mean, Median, and Standard Deviation for each row:")
print(mean_rows, median_rows, std_rows)


Mean, Median, and Standard Deviation:
-0.5 -0.5 3.8622100754188224
Mean, Median, and Standard Deviation for each column:
[-1.5  1.5 -1.5] [-1.5  1.5 -1.5] [2.5 3.5 4.5]
Mean, Median, and Standard Deviation for each row:
[ 0.66666667 -1.66666667] [ 1. -4.] [2.05480467 4.78423336]


Question 2(b): For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]).

 Find floor, ceiling and truncated value, rounded values

In [8]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])

print("floor values\n",np.floor(a),"\nceil values\n", np.ceil(a), "\ntruncated values\n",np.trunc(a), "\nrounded values\n",np.round(a))

floor values
 [-2. -2. -1.  0.  1.  1.  3.] 
ceil values
 [-1. -1. -0.  1.  2.  2.  3.] 
truncated values
 [-1. -1. -0.  0.  1.  1.  3.] 
rounded values
 [-2. -2. -0.  0.  2.  2.  3.]


Question 3(a):For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find

i. Sorted array

ii. Indices of sorted array

iii. 4 smallest elements

iv. 5 largest elements

In [13]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("Sorted array:")
print(np.sort(array))
print("Indices of sorted array:")
print(np.argsort(array))
print("4 smallest elements:")
print( np.partition(array, 4)[:4])
print("5 largest elements:")
print( np.partition(array, 4)[:5])


Sorted array:
[ 10  16  16  52  54  62 453]
Indices of sorted array:
[0 3 4 1 5 2 6]
4 smallest elements:
[16 10 16 52]
5 largest elements:
[16 10 16 52 54]


Question 3(b): For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find

i. Integer elements only

ii. Float elements only

In [16]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print("integers ",array[array % 1 == 0])
print("float ",array[array % 1 != 0])

integers  [1. 2. 3. 2.]
float  [1.2 2.2]


Q4: (a) Write a function named img_to_array(path) that reads an image from a specified path and save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale images)

In [17]:
from PIL import Image

In [28]:
text_file_path=""
def img_to_array(path):
    global text_file_path
    with Image.open(path) as img:
        img_array = np.array(img)
        if len(img_array.shape) == 3:
            img_type = 'RGB'
        elif len(img_array.shape) == 2:
            img_type = 'Grayscale'
        else:
            raise ValueError("Unsupported image format")

        img_array_text = np.array2string(img_array, separator=',', threshold=np.inf)

        text_file_path = path.rsplit('.', 1)[0] + '_array.txt'
        with open(text_file_path, 'w') as file:
            file.write(f"Image Type: {img_type}\n")
            file.write("Array Data:\n")
            file.write(img_array_text)

        print(f"Image array saved to {text_file_path}")

In [29]:
img_to_array('upload.png')

Image array saved to upload_array.txt


In [30]:
print(text_file_path)

upload_array.txt


In [33]:
with open(text_file_path, 'r') as file:
    file_content = file.read()
    print(file_content)

Image Type: Grayscale
Array Data:
[[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5,
   5, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9,10,20,20,20,20,20,20,20,20,10, 9, 9, 9,
   8, 8, 8, 7, 7, 7, 6, 5, 5, 4, 3, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 